name: End-to-end tests

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "51 * * * *"

defaults:
  run:
    shell: bash

env:
  K3D_VERSION: # 'v5.7.3' - optionally pin version
  K3D_CLUSTER_NAME: ${{ github.repository_owner }}-${{ github.event.repository.name }}-runner

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: 'kubewarden/kubewarden-end-to-end-tests'

    - name: "Create kubernetes cluster"
      run: |
        TAG=${{ env.K3D_VERSION }} sudo --preserve-env=TAG k3d-install
        k3d cluster create ${{ env.K3D_CLUSTER_NAME }} --agents 1

    # TODO: Use :latest images for nightly runs
    - name: Execute tests
      working-directory: ./kubewarden-end-to-end-tests
      run: |
        [[ "${{github.event_name}}" == 'schedule' ]] &&
        make KUBEWARDEN_CHARTS_LOCATION=../charts install \
          tests audit-scanner-installation.bats upgrade.bats

    - name: Clean Up
      if: always()
      run: |
        k3d cluster delete ${{ env.K3D_CLUSTER_NAME }}
