name: End-to-end tests

on:
  push:
    tags:
      - "*"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "51 * * * *"

defaults:
  run:
    shell: bash

env:
  K3D_VERSION: # 'v5.7.3' - optionally pin version
  K3D_CLUSTER_NAME: ${{ github.repository_owner }}-${{ github.event.repository.name }}-runner

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/checkout@v4
      with:
        repository: ${{ github.repository_owner }}/kubewarden-end-to-end-tests
        path: e2e-tests

    - name: "Create kubernetes cluster"
      run: |
        # TAG=${{ env.K3D_VERSION }} sudo --preserve-env=TAG k3d-install
        wget -q -O - https://raw.githubusercontent.com/k3d-io/k3d/main/install.sh | bash
        k3d cluster create ${{ env.K3D_CLUSTER_NAME }} --agents 1

    # TODO: Use :latest images for nightly runs
    - name: Execute tests
      working-directory: e2e-tests
      run: |
        make KUBEWARDEN_CHARTS_LOCATION=../charts \
          CLUSTER_NAME=${{ env.K3D_CLUSTER_NAME }} \
          install tests audit-scanner-installation.bats upgrade.bats
      # env:
        # CLUSTER_NAME: ${{ github.repository_owner }}-ghactions-cluster
    - name: Clean Up
      if: always()
      run: |
        k3d cluster delete ${{ env.K3D_CLUSTER_NAME }}
